edits

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -1,71 +1,53 @@
 #!/bin/bash
-inputFile="meanFile"
-column="meanCol"
-flag=0
-sum=0
-rows=0
-mean=0
-meanArr="meanArray"
+function generate(){
+  # NAME
+  #   generate - generate a matrix of a specified size
+  # SYNOPSIS
+  #   generate ROWS COLS RANGE
+  # DESCRIPTION
+  #   Outputs a matrix with ROWS and COLS as dimensions. If RANGE is an integer, the entries
+  #   of the matrix will be random integers in (-RANGE,+RANGE). If RANGE is a string starting
+  #   with 'Z' or 'z', the matrix will be populated with zeroes. If RANGE is a string starting
+  #   with 'O' or 'o', the matrix will be populated with ones. If RANGE is a string starting
+  #   with 'D' or 'd', the matrix will be a diagonal matrix with ones along the diagonal entries.
+  # AUTHOR
+  #   Written by Ryan Gambord (gambordr@oregonstate.edu)
 
+  [ $# -ne 3 ] && echo "invalid number of arguments" >&2      # This is equivalent to using an if statement.
+                                                              # The right side of the && operator will not
+                                                              # be evaluated unless the left side is true.
+  for arg in $1 $2
+  do
+    [[ $arg =~ [^0-9]+ ]] && echo "argument '$arg' is not an integer" >&2
+  done
 
-while IFS= read -rN1 char; do
-    if [[ "$char" == $'\n' ]]; 
-        then ((++rows))
-    fi
-done < $1
-
-((++rows))
-
-while read myLine
-do
-    echo -e "$myLine \n"
-    echo -e "$myLine" > $inputFile
-    cut -f 1 $inputFile > $column
-    cut -f 2 $inputFile >> $column
-    cut -f 3 $inputFile >> $column
-    cut -f 4 $inputFile >> $column
-    while read num
+  y=0
+  while [ $y -lt $1 ]
+  do
+    x=0
+    ((y++))
+    while [ $x -lt $2 ]
     do
-        sum=`expr $sum + $num`
-    done < $column
-    echo "sum: $sum"
-    sum=$(( $sum + $rows - 1 ))
-    mean=$(( $sum / $rows ))
-    echo "mean: $mean"
-    cat $mean >> $meanArr
-    mean=0
-    sum=0
-done < $1
-
-cat $meanArr
-
-# while IFS= read -rN1 char; do
-#     if [[ "$char" == $'\n' ]]; 
-#         then ((++rows))
-#     fi
-#     if [[ "$char" == $'\t' ]]; 
-#         then ((++columns))
-#     fi
-# done < "$1"
-
-# columns=$(( $columns / $rows))
-# ((columns++))
-# echo -e "\"$rows $columns\""
-
-# while read num
-# do
-#     echo "In loop"
-#     echo "num: $num"
-#     sum=`expr $sum + $num`
-#     echo "sum: $sum"
-#     echo -e "End of loop\n"
-
-# done < "$1"
-
-# while IFS= read -r line; do
-#     echo "Text read from file: $line"
-# done < "$1"
-
-
-# reference materials:
-# https://stackoverflow.com/questions/10929453/read-a-file-line-by-line-assigning-the-value-to-a-variable
+      ((x++))
+      case $3 in
+        [oO]*) echo -n 1;;
+        [zZ]*) echo -n 0;;
+        [dD]*) [ $x -eq $y ] && echo -n 1 || echo -n 0;;
+        *) if [[ "$3" =~ [^0-9]+ ]]
+             then
+               echo "invalid RANGE" >&2
+               exit 1
+             else
+               echo -n $(( (RANDOM - 32767 / 2) % $3 ))
+             fi;;
+      esac
+      if [ $x -ne $2 ]
+      then
+        echo -ne "\t"
+      else
+        echo
+      fi
+    done
+  done
+}
+generate $1 $2 $3
